In [1]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import pandas as pd
import numpy as np

In [2]:
iris = load_iris()
print(iris)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [3]:
print(iris.keys())

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [4]:
iris_data = iris.data
print(iris_data.shape)

(150, 4)


In [5]:
iris_label = iris.target
print(np.unique(iris_label))

[0 1 2]


In [6]:
iris_df = pd.DataFrame(iris_data,columns=iris.feature_names)
iris_df['label'] = iris.target
display(iris_df.head(3))

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)   
0                5.1               3.5                1.4               0.2  \
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   

   label  
0      0  
1      0  
2      0

In [7]:
x_train,x_test, y_train,y_test = train_test_split(
    iris_data,iris_label,test_size=0.2)
x_train.shape, x_test.shape,y_train.shape,y_test.shape

((120, 4), (30, 4), (120,), (30,))

In [8]:
dt_clf = DecisionTreeClassifier() #모델 생성

In [9]:
dt_clf.fit(x_train,y_train) #학습

DecisionTreeClassifier()

In [10]:
pred = dt_clf.predict(x_test) #예측

In [11]:
print(pred)
print(y_test)

[0 2 0 1 0 1 0 1 0 2 1 2 0 2 0 1 1 2 1 2 0 2 1 0 0 0 0 0 2 0]
[0 2 0 1 0 1 0 1 0 2 1 2 0 2 0 1 1 2 1 2 0 2 1 0 0 0 0 0 1 0]


In [12]:
print(f"accuracy:{accuracy_score(pred,y_test):.4f}")

accuracy:0.9667


## framework 익히기

In [13]:
from sklearn.datasets import load_iris

iris_data = load_iris()
print(type(iris))

<class 'sklearn.utils._bunch.Bunch'>


In [14]:
keys = iris_data.keys()
print("키 목록:",keys)

키 목록: dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [15]:
print("feature_names의 타입:",type(iris_data.feature_names))

feature_names의 타입: <class 'list'>


In [16]:
print("feature_names의 길이:",len(iris_data.feature_names))

feature_names의 길이: 4


In [17]:
print(iris_data.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [18]:
print("target_names의 타입:",type(iris_data.target_names))
print("target_names의 구조:",iris_data.target_names.shape)
print("target_names:",iris_data.target_names)

target_names의 타입: <class 'numpy.ndarray'>
target_names의 구조: (3,)
target_names: ['setosa' 'versicolor' 'virginica']


In [19]:
print("data의 타입:",type(iris_data.data))
print("data의 구조:",iris_data.data.shape)

data의 타입: <class 'numpy.ndarray'>
data의 구조: (150, 4)


In [20]:
print("target의 타입:",type(iris_data.target))
print("target의 구조:",iris_data.target.shape)

target의 타입: <class 'numpy.ndarray'>
target의 구조: (150,)


#### what is train_test_split()

In [24]:
xa  =[[x,x] for x in range(100)]
print(xa)
ya = [y for y in range(100)]
print(ya)

[[0, 0], [1, 1], [2, 2], [3, 3], [4, 4], [5, 5], [6, 6], [7, 7], [8, 8], [9, 9], [10, 10], [11, 11], [12, 12], [13, 13], [14, 14], [15, 15], [16, 16], [17, 17], [18, 18], [19, 19], [20, 20], [21, 21], [22, 22], [23, 23], [24, 24], [25, 25], [26, 26], [27, 27], [28, 28], [29, 29], [30, 30], [31, 31], [32, 32], [33, 33], [34, 34], [35, 35], [36, 36], [37, 37], [38, 38], [39, 39], [40, 40], [41, 41], [42, 42], [43, 43], [44, 44], [45, 45], [46, 46], [47, 47], [48, 48], [49, 49], [50, 50], [51, 51], [52, 52], [53, 53], [54, 54], [55, 55], [56, 56], [57, 57], [58, 58], [59, 59], [60, 60], [61, 61], [62, 62], [63, 63], [64, 64], [65, 65], [66, 66], [67, 67], [68, 68], [69, 69], [70, 70], [71, 71], [72, 72], [73, 73], [74, 74], [75, 75], [76, 76], [77, 77], [78, 78], [79, 79], [80, 80], [81, 81], [82, 82], [83, 83], [84, 84], [85, 85], [86, 86], [87, 87], [88, 88], [89, 89], [90, 90], [91, 91], [92, 92], [93, 93], [94, 94], [95, 95], [96, 96], [97, 97], [98, 98], [99, 99]]
[0, 1, 2, 3, 4, 5, 

In [22]:
x_train, x_test, y_train, y_test = train_test_split(xa,ya)

In [23]:
for i in range(len(x_train)):
    print(x_train[i], ":", y_train[i])

[45, 45] : 45
[19, 19] : 19
[71, 71] : 71
[22, 22] : 22
[63, 63] : 63
[91, 91] : 91
[83, 83] : 83
[95, 95] : 95
[16, 16] : 16
[15, 15] : 15
[74, 74] : 74
[69, 69] : 69
[49, 49] : 49
[20, 20] : 20
[39, 39] : 39
[40, 40] : 40
[29, 29] : 29
[23, 23] : 23
[56, 56] : 56
[44, 44] : 44
[18, 18] : 18
[41, 41] : 41
[7, 7] : 7
[81, 81] : 81
[10, 10] : 10
[38, 38] : 38
[75, 75] : 75
[62, 62] : 62
[3, 3] : 3
[90, 90] : 90
[17, 17] : 17
[14, 14] : 14
[37, 37] : 37
[67, 67] : 67
[33, 33] : 33
[89, 89] : 89
[27, 27] : 27
[48, 48] : 48
[2, 2] : 2
[87, 87] : 87
[21, 21] : 21
[72, 72] : 72
[65, 65] : 65
[52, 52] : 52
[76, 76] : 76
[64, 64] : 64
[0, 0] : 0
[78, 78] : 78
[36, 36] : 36
[32, 32] : 32
[46, 46] : 46
[84, 84] : 84
[5, 5] : 5
[1, 1] : 1
[25, 25] : 25
[11, 11] : 11
[47, 47] : 47
[59, 59] : 59
[28, 28] : 28
[97, 97] : 97
[35, 35] : 35
[54, 54] : 54
[82, 82] : 82
[73, 73] : 73
[12, 12] : 12
[9, 9] : 9
[70, 70] : 70
[92, 92] : 92
[88, 88] : 88
[24, 24] : 24
[53, 53] : 53
[55, 55] : 55
[26, 26] : 26

In [25]:
np.array(x_train).shape, np.array(y_train).shape

((75, 2), (75,))